#!/bin/bash

function deploy {
  cd _site &&
    git init &&
    git add . &&
    git cm -a -m "generated deploy" &&
    git remote add origin git@github.com:alisnic/alisnic.github.com.git &&
    git push -u origin master --force
}

read -p "Are you sure? " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
  deploy
fi
